name: Sync to Production

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Open-Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Production Repository
        run: |
          # Configure Git user profile for the commit history
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Force git to use the secret token for authentication
          git remote add production https://x-access-token:${{ secrets.SYNC_SENSE }}@github.com/kc-clintone/z01k-events.git
          
          # Push the main branch to Account A
          git push production main --force
